### ISSUE TITLE
Figure out name field questions one and for all!

### ISSUE THREAD

**Issue by bcomnes** [netlify/gocommerce-admin#19]
We are still confused as to what the best place is to source name information from on this project, so to close this issue, figure out it! 

Related: 
https://github.com/netlify/gocommerce/pull/143

**Comment by mraerino** [comment]
Should I give any input here?
I'd suggest this should become a configuration option that possibly takes a go template so it can be composed from multiple user metadata fields.

**Comment by bcomnes** [comment]
Yeah, neither of us (me and @RoseannaM) knew the answer even though we've discussed solutions a few times.  (I intended to tag both of you on the assignment, but I'm still waiting for collaborator invites to complete)

I'm on board with that suggestion.  Do we have existing issues for adding the option/template?

**Comment by mraerino** [comment]
The one my PR fixed was https://github.com/netlify/gocommerce/issues/120
There would need to be a new one extending on what my PR (https://github.com/netlify/gocommerce/pull/143) did.

**Comment by bcomnes** [comment]
Can someone unassigned me on this?  I can't for some reason.

**Comment by bcomnes** [comment]
Ping ping ^^

**Comment by bcomnes** [comment]
I'm going to close this to get this out of my assigned issues list, feel free to reopen if needed.
